[project]
name = "geo-trax"
version = "0.5.0"
description = "A Comprehensive Framework for Georeferenced Vehicle Trajectory Extraction from Drone Imagery"
authors = [
    { name = "Robert Fonod", email = "robert.fonod@ieee.org" },
]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
keywords = ["trajectory-extraction", "trajectory-analysis", "object-detection", "object-tracking", "object-stabilization", "georeferencing", "computer-vision", "deep-learning"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",        
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",    
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",    
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development",
    "Topic :: Multimedia :: Video",
]
dependencies = [
    "ultralytics==8.0.209",
    "lapx>=0.5.2",
    "stabilo>=1.0.1",
    "geopandas>=1.0.0",
    "numpy>=1.26.4,<2.0",
    "torch>=1.10.0,<2.6"
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.0",
    "scikit-image>=0.25.0",
    "comet_ml",
    "albumentations>=1.3.1",
    "onnx>=1.12.0",
    "onnxsim>=0.4.1",
    "thop>=0.1.1",
    "pycocotools>=2.0.6",
    "pyproj>=3.6.1"
]

[project.urls]
Homepage = "https://github.com/rfonod/geo-trax/"
Repository = "https://github.com/rfonod/geo-trax/"
Changelog = "https://github.com/rfonod/geo-trax/releases"
Issues = "https://github.com/rfonod/geo-trax/issues/"

[tool.ruff]
line-length = 120

[tool.ruff.lint]
select = ['E', 'F', 'W', 'A', "B", 'PLC', 'PLE', 'PLW', 'I']

[tool.ruff.format]
docstring-code-format = true
quote-style = "preserve"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = [
    "tests",
]

[tool.setuptools]
packages = ["utils"]