#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Author: Robert Fonod (robert.fonod@ieee.org)

"""
visualize.py - Video Visualization Tool

This script visualizes tracking results by overlaying them on the original video frames.
It supports various visualization options, including showing bounding boxes, class labels, tracking lines, confidence values,
speed estimates, and lane numbers. The script can also save the annotated video to a file or display it in real-time.
It is designed to work with the results generated by the extraction stage ('geotrax extract'), which processes
video files and generates tracking data in a specific format. If georeferenced results are available, the script can also visualize speed estimates and lane numbers.

Five rendering modes are available (see --viz-mode): the annotations can be drawn on the original frame (0),
the stabilized frame (1), or the static reference frame (2). Modes 3 and 4 instead draw a rotated bounding box
per vehicle, sized to its estimated physical dimensions and rotated to its per-frame heading (computed from the
camera-motion-free stabilized trajectory), projected back onto the original frame (3) or drawn directly on the
stabilized frame (4); both require stabilization.

Usage:
  geotrax visualize <source> [options]

Arguments:
  source : Path to the input video file.

Options:
  --help, -h          : Show this help message and exit.
  --cfg, -c <path>    : Path to a custom pipeline config file. Defaults to the bundled config;
                        run 'geotrax config show' to view it or 'geotrax config copy' to customize.
  --output-folder, -of <str> : Root folder for outputs (bare name or absolute path).
                        Defaults to cfg -> output -> folder (historical default: 'results').
  --model, -m <str>   : Detection model used to resolve vehicle class names — a local file path
                        OR an 'hf://<org>/<repo>/<path/to/file>.pt' Hugging Face reference. Only needed
                        when class names are not set via --class-names or cfg -> extraction ->
                        class_rename. Defaults to cfg -> extraction -> model.
  --class-names, -cn <ID=NAME|FILE> [...] : Class-id -> name mapping: a .yaml/.json file or
                        inline ID=NAME pairs (e.g. -cn 0=car 1=bus). Overrides model-derived
                        names. Defaults to cfg -> extraction -> class_rename, then model names.
  --log-path, -lp <str> : Where to write logs: a directory or a full file path; defaults to a platform-specific log directory.
  --verbose, -v       : Set print verbosity level to INFO (default: WARNING).

Visualization Options:
  --save / --no-save, -s  : Save the annotated output video to file. Defaults to cfg -> visualization -> save.
  --show / --no-show, -sh : Open a live preview window during processing. Defaults to cfg -> visualization -> show.
  --viz-mode, -vm <int> [<int> ...] : Frame source(s) for annotation: 0=original, 1=stabilized,
                        2=reference frame, 3=rotated boxes on the original frame,
                        4=rotated boxes on the stabilized frame (3 and 4 rotate each box to
                        the vehicle's per-frame heading; both require stabilization).
                        Accepts multiple values (e.g. 0 1 4) to render one video per mode.
                        Defaults to cfg -> visualization -> viz_mode.
  --plot-trajectories, -pt : Overlay trajectory positions on the first frame.
                        Defaults to cfg -> visualization -> plot_trajectories.
  --plot-delay, -pd <int> : Number of frames to display the trajectory overlay; only relevant when
                        --plot-trajectories is enabled. Defaults to cfg -> visualization -> plot_delay.
  --show-conf, -sc    : Include detection confidence in bounding-box labels. Defaults to cfg -> visualization -> show_conf.
  --show-lanes, -sl   : Include lane ID in bounding-box labels. Defaults to cfg -> visualization -> show_lanes.
  --show-class-names, -scn : Include vehicle class name in bounding-box labels. Defaults to cfg -> visualization -> show_class_names.
  --hide-labels, -hl  : Suppress all label text overlays. Defaults to cfg -> visualization -> hide_labels.
  --hide-tracks, -ht  : Suppress track tail lines. Defaults to cfg -> visualization -> hide_tracks.
  --hide-speed, -hs   : Suppress speed values in labels. Defaults to cfg -> visualization -> hide_speed.
  --speed-unit, -su <choice> : Speed display unit: km/h or mi/h. Defaults to cfg -> visualization -> speed_unit.
  --speed-deadzone, -sdz <float> : Floor displayed speeds <= this value (in the chosen speed unit) to 0; 0 disables. Defaults to cfg -> visualization -> speed_deadzone.
  --class-filter, -cf <int> [<int> ...] : Vehicle class IDs to exclude (e.g., -cf 1 2). Defaults to cfg -> visualization -> class_filter.
  --tail-length, -tl <int> : Number of past positions drawn as a fading track trail [frames]; [1, inf). Defaults to cfg -> visualization -> tail_length.
  --line-width, -lw <int> : Bounding-box and track stroke width [px]; [1, inf). Defaults to cfg -> visualization -> line_width.
  --heading-smoothing, -hsm <int> : (modes 3, 4) Gaussian smoothing window [frames] for the per-frame heading; larger = steadier, slower to follow turns. Defaults to cfg -> visualization -> heading_smoothing.
  --heading-min-speed, -hms <float> : (modes 3, 4) Minimum smoothed pixel speed [px/frame] for a reliable heading; below this the heading is held from the last reliable frame. Defaults to cfg -> visualization -> heading_min_speed.
  --cut-frame-left, -cfl <int> : Skip the first N frames. Defaults to cfg -> processing -> cut_frame_left.
  --cut-frame-right, -cfr <int> : Stop processing after this frame. Defaults to cfg -> processing -> cut_frame_right.

Examples:
1. Visualize the tracking results on a video using the default settings:
   geotrax visualize path/to/video.mp4 --show

2. Save with confidence values and exclude class 0 (default: car):
   geotrax visualize path/to/video.mp4 --save --class-filter 0 --show-conf

3. Hide labels, trajectory trails, and exclude multiple classes:
   geotrax visualize path/to/video.mp4 --show --hide-labels --hide-tracks --class-filter 1 2

4. Save with class names and cut off the first 100 frames:
   geotrax visualize path/to/video.mp4 --save --show-class-names --cut-frame-left 100

5. Visualize tracking results on a stabilized video without speed estimates:
   geotrax visualize path/to/video.mp4 --show --viz-mode 1 --hide-speed

6. Rename class labels in the visualization output:
   geotrax visualize path/to/video.mp4 --show -cn 0=vehicle 1=bus 2=truck 3=bike

7. Render rotated bounding boxes aligned to each vehicle's heading (requires stabilization):
   geotrax visualize path/to/video.mp4 --save --viz-mode 3      # on the original frame
   geotrax visualize path/to/video.mp4 --save --viz-mode 4      # on the stabilized frame

Notes:
- The script reads tracking results from '<stem><tracks_postfix>.txt' in the output folder (default: 'results/').
  Output folder and postfixes are configured via cfg -> output; use --output-folder to redirect at runtime.
- For --viz-mode 1, 3, and 4, transformation matrices are read from '<stem><stab_transform_postfix>.txt' in the same folder.
- Press 'q' during visualization to stop (with --show).
"""

import argparse
import logging
import shutil
import sys
from collections import defaultdict
from pathlib import Path

import cv2
import numpy as np
import pandas as pd
from scipy.ndimage import gaussian_filter1d
from tqdm import tqdm

from geotrax.utils.cli_utils import add_common_args
from geotrax.utils.config_utils import backfill_args_from_config, load_config, load_config_all
from geotrax.utils.data_utils import VizColors
from geotrax.utils.file_utils import (
    build_result_path,
    check_if_results_exist,
    detect_delimiter,
    determine_suffix_and_fourcc,
    get_output_dir,
)
from geotrax.utils.logging_utils import setup_logger


def visualize_results(args: argparse.Namespace, logger: logging.Logger) -> None:
    """
    Visualize the tracking results on a video.
    """
    config = load_config_all(args, logger)['main']
    viz = config['visualization']
    proc = config['processing']
    out_cfg_raw = config.get('output', {})
    backfill_args_from_config(args, {
        'save': viz['save'],
        'show': viz['show'],
        'viz_mode': viz['viz_mode'],
        'plot_trajectories': viz['plot_trajectories'],
        'plot_delay': viz['plot_delay'],
        'show_conf': viz['show_conf'],
        'show_lanes': viz['show_lanes'],
        'show_class_names': viz['show_class_names'],
        'hide_labels': viz['hide_labels'],
        'hide_tracks': viz['hide_tracks'],
        'hide_speed': viz['hide_speed'],
        'speed_unit': viz['speed_unit'],
        'speed_deadzone': viz['speed_deadzone'],
        'class_filter': viz['class_filter'],
        'tail_length': viz['tail_length'],
        'line_width': viz['line_width'],
        'heading_smoothing': viz['heading_smoothing'],
        'heading_min_speed': viz['heading_min_speed'],
        'cut_frame_left': proc['cut_frame_left'],
        'cut_frame_right': proc['cut_frame_right'],
        'output_folder': out_cfg_raw.get('folder', 'results'),
    })
    out_cfg = {**out_cfg_raw, 'folder': args.output_folder}
    if not args.save and not args.show:
        logger.warning("Neither --save nor --show is enabled. Visualization will run but produce no output. "
                       "Set 'save' or 'show' in the config file, or pass --save / --show on the command line.")
    class_names = config['class_names']
    viz_config = config['visualization']
    viz_config['tail_length'] = args.tail_length
    viz_config['line_width'] = args.line_width

    viz_modes = normalize_viz_modes(args.viz_mode, logger)
    for viz_mode in viz_modes:
        args.viz_mode = viz_mode
        tracks_txt_filepath, transforms_filepath, tracks_csv_filepath = get_and_verify_filepaths(args, logger, out_cfg)
        tracks, tracks_plotting = read_tracks(tracks_txt_filepath, class_names, args, logger)
        transforms = read_transforms(transforms_filepath, logger)
        speed_lane_data = read_georeferenced_results(tracks_csv_filepath, tracks, logger)
        vid_reader, vid_writer, pbar = initialize_streams(args, logger, out_cfg)

        frame_num = 0
        try:
            for frame_num, annotated_frame in process_frames(tracks, tracks_plotting, transforms, speed_lane_data, vid_reader, pbar, class_names, viz_config, args, logger):
                if args.show:
                    display_frame(annotated_frame, frame_num, logger)
                if args.save:
                    save_frame(vid_writer, annotated_frame, logger)
        except Exception as e:
            logger.error(f"An error occurred: {e}")
        finally:
            finalize_video(vid_reader, vid_writer, pbar, frame_num, args.show, logger)

    args.viz_mode = viz_modes


def resolve_viz_modes(args: argparse.Namespace, logger: logging.Logger) -> list:
    """
    Return the normalized visualization modes, reading the config default when --viz-mode
    was not given on the command line. Used by callers (e.g. batch_process) that need the
    modes before the full config is otherwise loaded; the resolved value is cached on args.
    """
    if args.viz_mode is None:
        args.viz_mode = load_config(args.cfg, logger)['visualization']['viz_mode']
    return normalize_viz_modes(args.viz_mode, logger)


def normalize_viz_modes(viz_mode, logger: logging.Logger) -> list:
    """
    Coerce a single visualization mode or a list of modes into an ordered, de-duplicated list.
    """
    modes = list(viz_mode) if isinstance(viz_mode, (list, tuple)) else [viz_mode]
    valid_modes = []
    for mode in modes:
        if mode not in (0, 1, 2, 3, 4):
            logger.critical(
                f"Invalid visualization mode '{mode}'. Valid modes are 0 (original), 1 (stabilized), "
                f"2 (reference), 3 (rotated boxes on the original frame), "
                f"4 (rotated boxes on the stabilized frame)."
            )
            sys.exit(1)
        if mode not in valid_modes:
            valid_modes.append(mode)
    if not valid_modes:
        logger.critical("No visualization mode specified.")
        sys.exit(1)
    return valid_modes


def process_frames(tracks: pd.DataFrame, tracks_plotting: pd.DataFrame, transforms: dict, speed_lane_data: pd.DataFrame, cap: cv2.VideoCapture, pbar: tqdm, class_names: dict, viz_config: dict, args: argparse.Namespace, logger: logging.Logger):
    """
    Process the video frames and annotate them with tracking results.
    """
    track_history = defaultdict(list)
    frame_num = 0
    viz_phase = args.plot_trajectories  # 0: normal processing phase, 1: trajectory plotting phase
    trajectory_frame = None
    ref_frame = None

    # Pre-group by frame so each iteration is a dict lookup instead of a full-table scan
    tracks_by_frame = dict(tuple(tracks.groupby(0)))
    if speed_lane_data is not None:
        speed_lane_by_frame = {
            frame_id: group.drop(columns=['Frame_ID']).astype({'Vehicle_ID': int}).set_index('Vehicle_ID')
            for frame_id, group in speed_lane_data.groupby('Frame_ID')
        }
    else:
        speed_lane_by_frame = None
    empty_tracks_frame = tracks.iloc[0:0]

    if viz_phase and tracks_plotting is not None:
        trajectory_frame = plot_trajectories(cap, tracks_plotting, args.cut_frame_left, args.cut_frame_right, viz_config, logger)

    while True:
        if viz_phase:
            # Trajectory plotting phase
            if frame_num < args.plot_delay:
                yield 0, trajectory_frame
                frame_num += 1
                continue
            else:
                cap.set(cv2.CAP_PROP_POS_FRAMES, 0)
                frame_num = 0
                viz_phase = 0
                continue

        # Normal video processing phase
        success, frame = cap.read()
        if not success:
            break

        if frame_num < args.cut_frame_left:
            frame_num += 1
            pbar.update()
            continue
        elif frame_num == args.cut_frame_left:
            ref_frame = frame.copy()
        elif args.cut_frame_right is not None and frame_num >= args.cut_frame_right:
            break

        tracks_frame = tracks_by_frame.get(frame_num, empty_tracks_frame)
        speed_lane_frame = speed_lane_by_frame.get(frame_num) if speed_lane_by_frame is not None else None

        Hinv = None
        if args.viz_mode in (1, 4) and frame_num in transforms:
            # Both modes warp the frame into stabilized space (same as mode 1); mode 4 then draws
            # the oriented box directly there (identity projection — the geometry is already stabilized).
            h, w = frame.shape[:2]
            frame = cv2.warpPerspective(frame, transforms[frame_num], (w, h))
        elif args.viz_mode == 2:
            if ref_frame is not None:
                frame = ref_frame.copy()
        elif args.viz_mode == 3:
            # Oriented boxes are built in stabilized space and projected back onto the original
            # frame; the reference frame (and any missing frame) maps with the identity.
            M = transforms.get(frame_num) if transforms is not None else None
            Hinv = (np.linalg.inv(M) if M is not None else np.eye(3)).astype(np.float32)
        if args.viz_mode == 4:
            Hinv = np.eye(3, dtype=np.float32)

        annotated_frame = annotate_frame(frame, frame_num, tracks_frame, track_history, class_names, speed_lane_frame, viz_config, args, logger, Hinv)
        yield frame_num, annotated_frame

        if args.cut_frame_right is not None and frame_num >= args.cut_frame_right:
            break

        frame_num += 1
        pbar.update()


def get_and_verify_filepaths(args: argparse.Namespace, logger: logging.Logger, output_cfg: dict = None) -> tuple:
    """
    Get and verify the filepaths for the provided video and tracking and georeferenced results.
    """

    video_exists, video_filepath = check_if_results_exist(args.source, 'video')
    if not video_exists:
        logger.critical(f"Video file '{video_filepath}' not found.")
        sys.exit(1)

    tracks_txt_exist, tracks_txt_filepath = check_if_results_exist(args.source, 'processed', output_cfg=output_cfg)
    if not tracks_txt_exist:
        logger.critical(f"Tracking results file '{tracks_txt_filepath}' not found. Make sure you have run the extraction stage ('geotrax extract').")
        sys.exit(1)

    if args.viz_mode in (1, 3, 4):
        transforms_exist, transforms_filepath = check_if_results_exist(args.source, 'video_transformations', output_cfg=output_cfg)
        if not transforms_exist:
            logger.critical(f"Transformation file '{transforms_filepath}' not found. Make sure you have enabled stabilization and run the extraction stage ('geotrax extract').")
            sys.exit(1)
    else:
        transforms_filepath = None

    tracks_csv_exist, tracks_csv_filepath = check_if_results_exist(args.source, 'georeferenced', output_cfg=output_cfg)
    if not tracks_csv_exist:
        logger.warning(f"Georeferenced file '{tracks_csv_filepath}' not found. Speed estimates will not be visualized.")
        tracks_csv_filepath = None

    return tracks_txt_filepath, transforms_filepath, tracks_csv_filepath


def read_tracks(tracks_txt_filepath: Path, class_names: dict, args: argparse.Namespace, logger: logging.Logger) -> tuple:
    """
    Read the tracking results from the text file.
    """
    delimiter = detect_delimiter(tracks_txt_filepath)
    tracks = pd.read_csv(tracks_txt_filepath, header=None, delimiter=delimiter)

    if args.viz_mode in (3, 4):
        return read_tracks_oriented(tracks, tracks_txt_filepath, class_names, args, logger)

    if tracks.shape[1] == 10 or tracks.shape[1] == 14:
        # drop the last two columns (vehicle length and width)
        tracks = tracks.drop(tracks.columns[-2:], axis=1)
    if args.plot_trajectories and tracks.shape[1] < 11:
        logger.error(f"No stabilized bounding boxes found in: '{tracks_txt_filepath}'. Disable the trajectory plotting option or re-run the extraction stage ('geotrax extract').")
        sys.exit(1)
    tracks_plotting = tracks[[0, 6, 7, 10]].copy() if tracks.shape[1] >= 11 else None
    if tracks_plotting is not None:
        tracks_plotting.columns = list(range(tracks_plotting.shape[1]))
    if args.viz_mode > 0:
        if tracks.shape[1] < 11:
            logger.error(f"No stabilized bounding boxes found in: '{tracks_txt_filepath}'. Choose a different visualization mode or re-run the extraction stage ('geotrax extract').")
            sys.exit(1)
        tracks = tracks.drop(tracks.columns[2:6], axis=1)
    elif tracks.shape[1] > 10:
        tracks = tracks.drop(tracks.columns[6:10], axis=1)
    elif tracks.shape[1] < 7:
        logger.error(f"No valid tracking results found in: '{tracks_txt_filepath}'.")
        sys.exit(1)
    tracks.columns = list(range(tracks.shape[1]))

    if len(class_names) < tracks[6].max() + 1:
        logger.error(f"At least {tracks[6].max() + 1} class names must be provided. Current class names defined for the used model are {class_names.values()}.")
        sys.exit(1)

    return tracks, tracks_plotting


def _estimate_fallback_dims(tracks: pd.DataFrame) -> tuple:
    """
    Per-vehicle Q25 size estimates derived solely from raw bbox dimensions (cols 4, 5).

    Used as a fallback when the azimuth-filtered estimator in :func:`extract.estimate_vehicle_dimensions`
    could not produce estimates (NaN in cols 12/13). Mirrors that estimator's approach — length =
    longer bbox side, width = shorter side, aggregated at Q25 across the full track — but without
    azimuth filtering. Returns two Series aligned to ``tracks.index``.
    """
    tmp = pd.DataFrame({
        'l': tracks[[4, 5]].max(axis=1),
        'w': tracks[[4, 5]].min(axis=1),
        'id': tracks[1],
    })
    q25 = tmp.groupby('id')[['l', 'w']].transform(lambda x: np.percentile(x, 25))
    return q25['l'], q25['w']


def read_tracks_oriented(tracks: pd.DataFrame, tracks_txt_filepath: Path, class_names: dict, args: argparse.Namespace, logger: logging.Logger) -> tuple:
    """
    Build the slim per-row layout for the rotated box modes (3 and 4).

    Requires the full stabilized + dimension-estimate layout (14 columns). Emits columns
    ``[frame, id, stab_xc, stab_yc, length, width, class, conf, heading, is_fallback]`` where
    ``length`` / ``width`` are the best-fit estimates from :func:`extract.estimate_vehicle_dimensions`
    (cols 12/13), or — when those are NaN — a per-vehicle Q25 aggregate of the raw bbox extents
    from :func:`_estimate_fallback_dims`. ``heading`` is the per-frame smoothed travel direction
    (radians, image coordinates) from :func:`compute_headings`. ``is_fallback`` (col 9) is ``True``
    for rows where the best-fit estimator yielded no result; those boxes are drawn with a dashed
    outline by :func:`draw_oriented_box` to distinguish them visually.
    """
    if tracks.shape[1] < 14:
        logger.error(
            f"Visualization mode 3 requires stabilized tracks with dimension estimates (14 columns) "
            f"in: '{tracks_txt_filepath}'. Re-run the extraction stage ('geotrax extract') with "
            f"stabilization enabled."
        )
        sys.exit(1)

    tracks_plotting = tracks[[0, 6, 7, 10]].copy()
    tracks_plotting.columns = list(range(tracks_plotting.shape[1]))

    headings = compute_headings(tracks, args.heading_smoothing, args.heading_min_speed, logger)
    # Dimension fallback: where the best-fit estimate is NaN, use a per-vehicle Q25 of raw bbox dims.
    is_fallback = tracks[12].isna()
    fb_length, fb_width = _estimate_fallback_dims(tracks)
    length = tracks[12].where(~is_fallback, fb_length)
    width = tracks[13].where(~is_fallback, fb_width)

    oriented = pd.DataFrame({
        0: tracks[0],              # frame id
        1: tracks[1],              # vehicle id
        2: tracks[6],              # stabilized center x
        3: tracks[7],              # stabilized center y
        4: length,                 # best-fit length [px]
        5: width,                  # best-fit width [px]
        6: tracks[10],             # class id
        7: tracks[11],             # confidence
        8: headings,               # per-frame heading [rad, image coords]; NaN -> axis-aligned box
        9: is_fallback.astype(bool),  # True = raw-bbox fallback (dashed outline); False = estimated
    })

    if len(class_names) < oriented[6].max() + 1:
        logger.error(f"At least {oriented[6].max() + 1} class names must be provided. Current class names defined for the used model are {class_names.values()}.")
        sys.exit(1)

    return oriented, tracks_plotting


def compute_headings(tracks: pd.DataFrame, smoothing: float, min_speed: float, logger: logging.Logger) -> pd.Series:
    """
    Per-frame vehicle heading (radians, image coordinates, y-down) for the oriented box modes (3, 4).

    For each track, the stabilized center trajectory (columns 6, 7) is differentiated and the
    velocity components are smoothed with a Gaussian filter; the heading is ``arctan2(dy, dx)``.
    Frames whose smoothed pixel speed is below ``min_speed`` are unreliable and inherit the
    nearest reliable heading (held, never interpolated across the angle wraparound). A track that
    never moves enough (common in short clips) has no motion direction, so its heading falls back
    to the orientation of the longer raw bounding-box side (cols 4, 5): a detection taller than it
    is wide implies a vertically oriented vehicle (heading pi/2), otherwise horizontal (0). Returns
    a Series aligned to ``tracks.index``.
    """
    headings = pd.Series(np.nan, index=tracks.index, dtype=float)
    sigma = max(float(smoothing), 1e-6)
    for _, grp in tracks.groupby(1):
        grp = grp.sort_values(0)
        # Fallback when motion is unavailable: align the best-fit box with the longer HBB side.
        aspect_fallback = np.pi / 2 if np.median(grp[5]) > np.median(grp[4]) else 0.0
        if len(grp) < 2:
            headings.loc[grp.index] = aspect_fallback
            continue
        x = grp[6].to_numpy(dtype=float)
        y = grp[7].to_numpy(dtype=float)
        dx = gaussian_filter1d(np.gradient(x), sigma, mode='reflect')
        dy = gaussian_filter1d(np.gradient(y), sigma, mode='reflect')
        reliable = np.hypot(dx, dy) >= min_speed
        if not reliable.any():
            headings.loc[grp.index] = aspect_fallback  # stationary: orient by bbox aspect
            continue
        theta = np.where(reliable, np.arctan2(dy, dx), np.nan)
        theta = pd.Series(theta).ffill().bfill().to_numpy()  # hold heading over unreliable frames
        headings.loc[grp.index] = theta
    return headings


def read_transforms(transforms_filepath: Path, logger: logging.Logger) -> dict:
    """
    Read the transformation matrices from the text file.
    """
    if transforms_filepath is None:
        return None

    delimiter = detect_delimiter(transforms_filepath)
    transforms = np.loadtxt(transforms_filepath, delimiter=delimiter)

    if transforms.ndim == 1:
        transforms = transforms.reshape(1, -1)
    if transforms.shape[1] != 10:
        logger.error(f"Not valid transforms in: '{transforms_filepath}'.")
        sys.exit(1)

    frame_nums = transforms[:, 0].astype(int)
    matrices = transforms[:, 1:].reshape((-1, 3, 3))

    if not np.all(np.diff(frame_nums) == 1):
        logger.warning(f"Missing frame ids found in: '{transforms_filepath}'.")

    if not np.all(np.linalg.det(matrices) > 0):
        logger.error(f"Not valid transforms found in: '{transforms_filepath}'.")
        sys.exit(1)

    transforms = dict(zip(frame_nums, matrices))
    return transforms


def read_georeferenced_results(tracks_csv_filepath: Path, tracks: pd.DataFrame, logger: logging.Logger) -> pd.DataFrame:
    """
    Read the georeferenced tracking results from the CSV file.
    """
    if tracks_csv_filepath is None:
        return None

    georeferenced_data = pd.read_csv(tracks_csv_filepath)
    if 'Frame_Number' in georeferenced_data.columns:
        georeferenced_data.rename(columns={'Frame_Number': 'Frame_ID'}, inplace=True)
    elif 'Timestamp' in georeferenced_data.columns:
        start_frame = int(tracks[0].min())
        csv_timestamps = sorted(georeferenced_data['Timestamp'].unique())
        ts_to_frame = {ts: start_frame + i for i, ts in enumerate(csv_timestamps)}
        georeferenced_data['Frame_ID'] = georeferenced_data['Timestamp'].map(ts_to_frame)
        logger.warning(
            f"'Frame_Number' column missing from '{tracks_csv_filepath.name}'. "
            f"Frame IDs reconstructed from tracking results assuming no dropped frames. "
            f"Re-run 'geotrax georeference' to regenerate the CSV with proper frame numbers."
        )
    else:
        logger.warning(
            f"Neither 'Frame_Number' nor 'Timestamp' column found in '{tracks_csv_filepath.name}'. "
            f"Speed/lane data cannot be displayed. Re-run 'geotrax georeference' to regenerate the CSV."
        )
        return None
    georeferenced_data = georeferenced_data[['Frame_ID', 'Vehicle_ID', 'Vehicle_Speed', 'Lane_Number']]
    return georeferenced_data


def initialize_streams(args: argparse.Namespace, logger: logging.Logger, output_cfg: dict = None) -> tuple:
    """
    Initialize video reader, writer, and progress bar.
    """
    vid_reader = cv2.VideoCapture(str(args.source))
    if not vid_reader.isOpened():
        logger.error(f"Failed to open: '{args.source}'.")
        sys.exit(1)

    frame_count = int(vid_reader.get(cv2.CAP_PROP_FRAME_COUNT))
    if args.save:
        frame_width = int(vid_reader.get(cv2.CAP_PROP_FRAME_WIDTH))
        frame_height = int(vid_reader.get(cv2.CAP_PROP_FRAME_HEIGHT))
        fps = vid_reader.get(cv2.CAP_PROP_FPS) # int() might be required, floats might produce error in MP4 codec

        suffix, fourcc = determine_suffix_and_fourcc()
        out_path = build_result_path(args.source, 'visualized', output_cfg, args.viz_mode, suffix)
        get_output_dir(args.source, output_cfg).mkdir(parents=True, exist_ok=True)
        vid_file = str(out_path)

        vid_writer = cv2.VideoWriter(vid_file, cv2.VideoWriter_fourcc(*fourcc), fps, (frame_width, frame_height))
    else:
        vid_writer = None

    _bar_w = max(10, shutil.get_terminal_size().columns - 88)
    pbar = tqdm(total=frame_count, unit='f', leave=True, colour='green',
                desc=f'{args.source.name} - visualizing @ mode {args.viz_mode}',
                bar_format=f'{{l_bar}}{{bar:{_bar_w}}}{{r_bar}}')
    return vid_reader, vid_writer, pbar


def plot_trajectories(cap: cv2.VideoCapture, tracks: pd.DataFrame, cut_frame_left: int, cut_frame_right: int, viz_config: dict, logger: logging.Logger) -> np.ndarray:
    """
    Plot the trajectories on the reference frame with an alpha channel.
    """
    success, ref_frame = cap.read()
    if not success:
        logger.error("Failed to read the reference frame.")
        sys.exit(1)
    tracks_plot = tracks[tracks[0] >= cut_frame_left]
    if cut_frame_right is not None:
        tracks_plot = tracks_plot[tracks_plot[0] <= cut_frame_right]

    colors = VizColors()
    line_width = viz_config['line_width']
    overlay = ref_frame.copy()

    for _, row in tracks_plot.iterrows():
        xc_stab, yc_stab, c = row[1:4]
        color = colors(c, True)
        cv2.circle(overlay, (int(xc_stab), int(yc_stab)), 1, color, line_width)

    cv2.addWeighted(overlay, 0.75, ref_frame, 0.25, 0, ref_frame)

    return ref_frame


def annotate_frame(frame: np.ndarray, frame_num: int, tracks_frame: pd.DataFrame, track_history: dict, class_names: dict, speed_lane_frame: pd.DataFrame, viz_config: dict, args: argparse.Namespace, logger: logging.Logger, Hinv: np.ndarray = None) -> np.ndarray:
    """
    Annotate the frame with the tracking results.

    For the oriented box modes (3 and 4), ``tracks_frame`` carries the slim oriented layout
    (cols 2/3 = stabilized center, 4/5 = best-fit length/width, 8 = heading, 9 = is_fallback) and
    ``Hinv`` projects each box from stabilized space onto the rendered frame: the inverse
    stabilization homography for mode 3 (original frame), or the identity for mode 4
    (already-stabilized frame). Rows where col 9 is ``True`` used raw bbox dimensions and are
    drawn with a dashed outline via :func:`draw_oriented_box`.
    """
    tail_length = viz_config['tail_length']
    line_width = viz_config['line_width']
    colors = VizColors()
    annotated_frame = frame.copy()
    if tracks_frame.empty:
        logger.warning(f"No detection results for frame {frame_num:05d}")
        return annotated_frame

    is_oriented = args.viz_mode in (3, 4)
    ids = tracks_frame.iloc[:, 1].values
    Xcn, Ycn, Wn, Hn = tracks_frame.iloc[:, 2:6].values.T
    classes = tracks_frame.iloc[:, 6].values
    if is_oriented:
        scores = tracks_frame.iloc[:, 7].values
        headings = tracks_frame.iloc[:, 8].values
        fallbacks = tracks_frame.iloc[:, 9].values
    else:
        scores = tracks_frame.iloc[:, 7].values if tracks_frame.shape[1] == 8 else [''] * len(ids)
        headings = [None] * len(ids)
        fallbacks = [False] * len(ids)

    for track_id, xcn, ycn, wn, hn, c, s, heading, is_fb in zip(ids, Xcn, Ycn, Wn, Hn, classes, scores, headings, fallbacks):
        if args.class_filter and c in args.class_filter:
            continue

        speed, lane = None, None
        if speed_lane_frame is not None and int(track_id) in speed_lane_frame.index:
            vehicle_data = speed_lane_frame.loc[int(track_id)]
            if isinstance(vehicle_data, pd.DataFrame):  # duplicate Vehicle_ID in this frame
                vehicle_data = vehicle_data.iloc[0]
            speed = vehicle_data['Vehicle_Speed']
            lane = vehicle_data['Lane_Number']
            # Convert speed for visualization if mi/h is selected (data is stored in km/h)
            if not np.isnan(speed):
                if args.speed_unit == 'mi/h':
                    speed = int(speed * 0.621371)  # Convert km/h to mi/h
                else:
                    speed = int(speed)
                if speed <= args.speed_deadzone:  # Deadzone: floor near-stationary speeds to 0 (display only)
                    speed = 0
            else:
                speed = None
            lane = int(lane) if lane not in ('', None) and pd.notna(lane) else None

        color = colors(c, True)
        if is_oriented:
            # wn/hn carry the best-fit length/width; project the oriented box onto the original frame.
            x1n, y1n = draw_oriented_box(annotated_frame, xcn, ycn, wn, hn, heading, Hinv, color, line_width, is_fb)
            cx_draw, cy_draw = x1n, y1n
        else:
            x1n, y1n = int(xcn - wn / 2), int(ycn - hn / 2)
            x2n, y2n = int(xcn + wn / 2), int(ycn + hn / 2)
            cv2.rectangle(annotated_frame, (x1n, y1n), (x2n, y2n), color, line_width, lineType=cv2.LINE_AA)
            cx_draw, cy_draw = xcn, ycn

        if not args.hide_labels:
            label_parts = []
            if track_id not in {None, -1}:
                label_parts.append(f'id:{track_id}')
            if args.show_class_names:
                label_parts.append(class_names[c])
            if not args.hide_speed and speed is not None:
                label_parts.append(f'{speed} {args.speed_unit}')
            if args.show_lanes and lane is not None:
                label_parts.append(f'L{lane}')
            if args.show_conf and s != '':
                label_parts.append(f'{s:.2f}')
            label = ' '.join(label_parts)

            tf = max(line_width - 1, 1)
            twn, thn = cv2.getTextSize(label, 0, fontScale=line_width / 3, thickness=tf)[0]
            outside = y1n - thn >= 3
            xt2n = x1n + twn
            yt2n = y1n - thn - 3 if outside else y1n + thn + 3
            cv2.rectangle(annotated_frame, (x1n, y1n), (xt2n, yt2n), color, -1, cv2.LINE_AA)
            cv2.putText(annotated_frame, label, (x1n, y1n - 2 if outside else y1n + thn + 2),
                        0, line_width / 3, colors.txt_color, thickness=tf, lineType=cv2.LINE_AA)

        if not args.hide_tracks:
            track = track_history[track_id]
            track.append((float(cx_draw), float(cy_draw)))
            if len(track) > tail_length:
                track.pop(0)
            points = np.array(track, dtype=np.int32).reshape((-1, 1, 2))
            track_len = len(points)
            for i, point in enumerate(points):
                cv2.circle(annotated_frame, tuple(point[0]), int(1 + 8 * (i + 1) / track_len), color, line_width)
    return annotated_frame


def _draw_dashed_poly(frame: np.ndarray, corners: np.ndarray, color: tuple, thickness: int, dash: int = 10, gap: int = 5) -> None:
    """
    Draw a closed dashed polygon on ``frame`` by rendering each edge as alternating dash/gap segments.

    OpenCV has no native dashed-line API, so this walks each edge at pixel-level steps and draws
    only the ``dash``-length segments, leaving ``gap``-length gaps between them.
    """
    n = len(corners)
    for i in range(n):
        p1 = corners[i].astype(float)
        p2 = corners[(i + 1) % n].astype(float)
        dist = float(np.hypot(*(p2 - p1)))
        if dist < 1:
            continue
        direction = (p2 - p1) / dist
        t = 0.0
        while t < dist:
            t1 = min(t + dash, dist)
            a = (p1 + direction * t).astype(np.int32)
            b = (p1 + direction * t1).astype(np.int32)
            cv2.line(frame, tuple(a), tuple(b), color, thickness, cv2.LINE_AA)
            t += dash + gap


def draw_oriented_box(frame: np.ndarray, cx: float, cy: float, length: float, width: float, heading: float, Hinv: np.ndarray, color: tuple, line_width: int, is_fallback: bool = False) -> tuple:
    """
    Draw a rotated bounding box (visualization modes 3 and 4) and return its projected center.

    The box is built in stabilized image space (center ``cx, cy``; size ``length`` x ``width``;
    rotated to ``heading`` radians) and projected onto the rendered frame via ``Hinv`` (the inverse
    stabilization homography for mode 3, or the identity for mode 4), then drawn as a closed polygon
    with a short tick from the center toward the front edge to indicate travel direction. A NaN
    ``heading`` (no reliable motion) falls back to an axis-aligned box.

    When ``is_fallback`` is ``True`` the box dimensions come from the raw YOLO bounding box rather
    than the best-fit size estimator; in that case the outline is drawn dashed (via
    :func:`_draw_dashed_poly`) so viewers can immediately distinguish estimated from fallback boxes.
    """
    if heading is None or np.isnan(heading):
        ux, uy = 1.0, 0.0  # axis-aligned fallback when the heading is unknown
    else:
        ux, uy = np.cos(heading), np.sin(heading)
    vx, vy = -uy, ux  # width axis, perpendicular to the heading
    hl, hw = length / 2.0, width / 2.0

    # Corners (front-left, front-right, rear-right, rear-left) + front-edge midpoint + center.
    pts = np.array([
        [cx + hl * ux - hw * vx, cy + hl * uy - hw * vy],
        [cx + hl * ux + hw * vx, cy + hl * uy + hw * vy],
        [cx - hl * ux + hw * vx, cy - hl * uy + hw * vy],
        [cx - hl * ux - hw * vx, cy - hl * uy - hw * vy],
        [cx + hl * ux, cy + hl * uy],
        [cx, cy],
    ], dtype=np.float32).reshape(-1, 1, 2)

    proj = cv2.perspectiveTransform(pts, Hinv).reshape(-1, 2).astype(np.int32)
    corners, front, center = proj[:4], proj[4], proj[5]

    if is_fallback:
        _draw_dashed_poly(frame, corners, color, line_width)
    else:
        cv2.polylines(frame, [corners.reshape(-1, 1, 2)], isClosed=True, color=color, thickness=line_width, lineType=cv2.LINE_AA)
    cv2.line(frame, tuple(center), tuple(front), color, line_width, lineType=cv2.LINE_AA)
    return int(center[0]), int(center[1])


def display_frame(annotated_frame: np.ndarray, frame_num: int, logger: logging.Logger) -> None:
    """
    Display the annotated frame.
    """
    cv2.putText(annotated_frame, f'Frame {frame_num:05d}', org=(20, 50),
                    fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1.5, thickness=2, color=(0, 255, 100))
    cv2.putText(annotated_frame, '(Press <q> to stop)', org=(375, 50),
        fontFace=cv2.FONT_HERSHEY_SIMPLEX, fontScale=1.5, thickness=2, color=(0, 125, 255))
    cv2.imshow("YOLOv8 Tracking", annotated_frame)

    if cv2.waitKey(1) == ord('q'):
        logger.warning('Visualization interrupted by user.')
        raise KeyboardInterrupt


def save_frame(vid_writer: cv2.VideoWriter, annotated_frame: np.ndarray, logger: logging.Logger) -> None:
    """
    Save the annotated frame to the video file.
    """
    try:
        vid_writer.write(annotated_frame)
    except cv2.error as e:
        logger.error(f'Failed to write frame to video: {e}')
        sys.exit(1)


def finalize_video(vid_reader: cv2.VideoCapture, vid_writer: cv2.VideoWriter, pbar: tqdm, frame_num: int, show: bool, logger: logging.Logger) -> None:
    """
    Finalize the video processing.
    """
    vid_reader.release()
    if vid_writer is not None:
        vid_writer.release()
        logger.info('Visualization video saved successfully')
    if show:
        cv2.destroyAllWindows()
    pbar.total = frame_num + 1
    pbar.n = frame_num + 1
    pbar.refresh()
    pbar.set_postfix_str('done')
    pbar.close()


def add_visualization_args(group, include_frame_range: bool = True) -> None:
    """
    Register the shared visualization CLI flags on the given argparse parser/group.

    Used by both ``geotrax visualize`` and ``geotrax batch`` so the two commands expose an
    identical set of visualization options (single source of truth, no drift). Every flag
    defaults to ``None`` and is backfilled from the config in ``visualize_results``.

    ``include_frame_range`` adds ``--cut-frame-left``/``--cut-frame-right``; batch sets it to
    ``False`` since it registers those under its processing options instead.
    """
    group.add_argument('--save', '-s', action=argparse.BooleanOptionalAction, default=None,
                       help='Save the annotated output video to file. Defaults to cfg -> visualization -> save.')
    group.add_argument('--show', '-sh', action=argparse.BooleanOptionalAction, default=None,
                       help='Open a live preview window during processing. Defaults to cfg -> visualization -> show.')
    group.add_argument('--viz-mode', '-vm', type=int, nargs='+', default=None, choices=[0, 1, 2, 3, 4], metavar='MODE',
                       help='Frame source(s) for annotation: 0=original, 1=stabilized, 2=reference frame, 3=rotated boxes on the original frame, 4=rotated boxes on the stabilized frame (3 and 4 rotate each box to the vehicle\'s per-frame heading; both require stabilization). Accepts multiple values, e.g. "--viz-mode 0 1 4" renders one video per mode. Defaults to cfg -> visualization -> viz_mode.')
    group.add_argument('--plot-trajectories', '-pt', action=argparse.BooleanOptionalAction, default=None,
                       help='Overlay trajectory positions on the first frame. Defaults to cfg -> visualization -> plot_trajectories.')
    group.add_argument('--plot-delay', '-pd', type=int, default=None,
                       help='Number of frames to display the trajectory overlay; only relevant when --plot-trajectories is enabled. Defaults to cfg -> visualization -> plot_delay.')
    group.add_argument('--show-conf', '-sc', action=argparse.BooleanOptionalAction, default=None,
                       help='Include detection confidence in bounding-box labels. Defaults to cfg -> visualization -> show_conf.')
    group.add_argument('--show-lanes', '-sl', action=argparse.BooleanOptionalAction, default=None,
                       help='Include lane ID in bounding-box labels. Defaults to cfg -> visualization -> show_lanes.')
    group.add_argument('--show-class-names', '-scn', action=argparse.BooleanOptionalAction, default=None,
                       help='Include vehicle class name in bounding-box labels. Defaults to cfg -> visualization -> show_class_names.')
    group.add_argument('--hide-labels', '-hl', action=argparse.BooleanOptionalAction, default=None,
                       help='Suppress all label text overlays. Defaults to cfg -> visualization -> hide_labels.')
    group.add_argument('--hide-tracks', '-ht', action=argparse.BooleanOptionalAction, default=None,
                       help='Suppress track tail lines. Defaults to cfg -> visualization -> hide_tracks.')
    group.add_argument('--hide-speed', '-hs', action=argparse.BooleanOptionalAction, default=None,
                       help='Suppress speed values in labels. Defaults to cfg -> visualization -> hide_speed.')
    group.add_argument('--speed-unit', '-su', type=str, default=None, choices=['km/h', 'mi/h'],
                       help='Speed display unit: km/h or mi/h. Defaults to cfg -> visualization -> speed_unit.')
    group.add_argument('--speed-deadzone', '-sdz', type=float, default=None,
                       help='Floor displayed speeds at or below this value (in the chosen speed unit) to 0, hiding stationary-vehicle jitter; 0 disables. Defaults to cfg -> visualization -> speed_deadzone.')
    group.add_argument('--class-filter', '-cf', type=int, nargs='+', default=None,
                       help='Vehicle class IDs to exclude from visualization (e.g., -cf 1 2). Defaults to cfg -> visualization -> class_filter.')
    group.add_argument('--tail-length', '-tl', type=int, default=None,
                       help='Number of past positions drawn as a fading track trail [frames]; [1, inf). Defaults to cfg -> visualization -> tail_length.')
    group.add_argument('--line-width', '-lw', type=int, default=None,
                       help='Bounding-box and track stroke width [px]; [1, inf). Defaults to cfg -> visualization -> line_width.')
    group.add_argument('--heading-smoothing', '-hsm', type=int, default=None,
                       help='(modes 3, 4) Gaussian smoothing window [frames] for the per-frame heading; larger = steadier, slower to follow turns. Defaults to cfg -> visualization -> heading_smoothing.')
    group.add_argument('--heading-min-speed', '-hms', type=float, default=None,
                       help='(modes 3, 4) Minimum smoothed pixel speed [px/frame] for a reliable heading; below this the heading is held from the last reliable frame. Defaults to cfg -> visualization -> heading_min_speed.')
    if include_frame_range:
        group.add_argument('--cut-frame-left', '-cfl', type=int, default=None,
                           help='Skip the first N frames. Defaults to cfg -> processing -> cut_frame_left.')
        group.add_argument('--cut-frame-right', '-cfr', type=int, default=None,
                           help='Stop processing after this frame. Defaults to cfg -> processing -> cut_frame_right.')


def parse_cli_args() -> argparse.Namespace:
    """
    Parse command-line arguments
    """
    parser = argparse.ArgumentParser(description='Tracking Results Visualization')

    parser.add_argument('source', type=Path, help='Path to the input video file.')

    optional = parser.add_argument_group('Optional arguments')
    add_common_args(optional)
    optional.add_argument('--model', '-m', nargs='+', default=None, metavar='MODEL', help="Detection model used to resolve vehicle class names: a local path OR an 'hf://<org>/<repo>/<path/to/file>.pt' reference. Defaults to cfg -> extraction -> model.")
    optional.add_argument('--class-names', '-cn', nargs='+', default=None, metavar='ID=NAME|FILE', help="Class-id -> name mapping: a .yaml/.json file or inline ID=NAME pairs (e.g. -cn 0=car 1=bus). Defaults to cfg -> extraction -> class_rename, then model names.")

    viz = parser.add_argument_group('Visualization arguments')
    add_visualization_args(viz)

    return parser.parse_args()

def main() -> None:
    """
    Command-line entry point.
    """
    args = parse_cli_args()
    logger = setup_logger(__name__, args.verbose, args.log_path)

    visualize_results(args, logger)


if __name__ == '__main__':
    main()
